apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-monnom-MonApplication-backend-cert
  namespace: staging-monnom-MonApplication-backend
spec:
  secretName: staging-monnom-MonApplication-backend-tls
  dnsNames:
    - staging.monsousdomain2.api.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
