apiVersion: v1
kind: Service
metadata:
  name: prod-monnom-MonApplication-backend-service
  namespace: prod-monnom-MonApplication-backend
spec:
  ports:
    - port: 3333
      targetPort: 3333
  selector:
    app: prod-monnom-MonApplication-backend
